[package]
name = "mingrep_cx"
version = "0.1.0"
authors = ["cx <17367073440@163.com>"]
edition = "2018"
description = "cx test mingrep,find file match contents"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
